# Generated by Django 4.1.7 on 2023-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
